// Generated by https://quicktype.io

export interface Products {
    id:   string;
    name: string;
    data: Data;
}

export interface Data {
    price:   number;
    year:    string;
    color?:  string;
}

export interface ProductData {
    productName: string,
    productYear: string,
    productPrice: number
}
