// Generated by https://quicktype.io

export interface Products {
    id:   string;
    name: string;
    data: Data;
}

export interface Data {
    price?:         number;
    color?:         string;
    generation?:    string;
    Capacity?:      string;
    "Screen size"?: number;
    Generation?:    string;
    Price?:         string;
}
